### ISSUE TITLE
Change outputPaths to accept extension

### ISSUE THREAD

**Issue by casio** [n1ru4l/ember-cli-css-preprocess#21]
Say I have both, an `app.css`(for being processed by postcss) and an `app.scss` that imports a sass based library. I'd like them both to be output to a single sheet(but would also be happy w/ two processed files, really).

I just checked that out by using multiple processors in `styleProcessorOptions.processors` and it seems, I can only either use `css` **or** `scss` here, because `styleProcessorOptions.extension` seems to prevent that.
Also tried the`file` attr of a processor but that seemed to be ignored completely.

What am I doing wrong? : )

**Comment by n1ru4l** [comment]
http://ember-cli.com/user-guide/#configuring-output-paths

Have you tried this?
```javascript
var app = new EmberApp(defaults, {
    // Add options here
    styleProcessorOptions: {
		processors: [{
			type: 'postcss',
			parser: require('postcss-scss'),
			filter: ['app.css', 'nested/*', '!nested/blub.css'],
			plugins: [
				{
					module: require('autoprefixer'),
					options: {
                		browsers: [
							'last 2 versions'
                		]
              		}
					},
				{
				module: require('precss'),
				options: {}
			}
		]
	},
	extension: 'css'
	},
  	outputPaths: {
    	app: {
			css: {
				'app': 'assets/lel.css',
				'amk': 'assets/toll.css',
				'trolol': 'assets/foo.css'
			}
		}
	}
```
This is my 'test'-setup, it will process 3 files in the styles folder (app.css, amk.css, trolol.css). (Please ignore the filter property it will be a v1.0 feature.)

I am also going to do some research on how to handle multiple file extensions this week. For know you must stick with one, maybe you could do some hacky trick like naming your *.scss file to *scss.css (for the moment).

**Comment by n1ru4l** [comment]
```javascript
var app = new EmberApp(defaults, {
    // Add options here
    styleProcessorOptions: {
		processors: [{
			type: 'postcss',
			parser: require('postcss-scss'),
			filter: ['app.css', 'nested/*', '!nested/blub.css'],
			plugins: [
				{
					module: require('autoprefixer'),
					options: {
                		browsers: [
							'last 2 versions'
                		]
              		}
					},
				{
				module: require('precss'),
				options: {}
			}
		]
	},
	extension: 'css'
	},
  	outputPaths: {
    	app: {
			css: {
				'app.css': 'assets/lel.css',
				'amk.scss': 'assets/toll.css',
				'trolol.less': 'assets/foo.css'
			}
		}
	}
```
This would be the easiest approach for this problem. 
I'm going to implement this in v1.0

**Comment by casio** [comment]
Thanks for the info! I can confirm the above is working for some simple test files I just created.

However, my usecase would be to have one npm managed sass library(`.scss`, preferably using node-sass) plus my own projects styles using postcss(`.css`, w/ postcss-import, etc), yielding one app sheet.

Happy to help testing, if your research on multiple extensions brings up something!

**Comment by n1ru4l** [comment]
This can be achieved by configuring a processor to parse specific files only.
https://github.com/n1ru4l/ember-cli-css-preprocess#setup-processor-to-parse-specific-files-only

In v1.0 the file filter will also support the glob pattern which gives you the posibility to tell a processor to parse *.scss files only or *.css.

**Comment by n1ru4l** [comment]
Done.
