### ISSUE TITLE
Not based on ember-cli addon structure

### ISSUE THREAD

**Issue by pichfl** [n1ru4l/ember-cli-css-preprocess#33]
Is there a reason this plugin uses gulp for development over the usual ember-cli addon build process?

If not, happy to file a pull request to make this happen.

**Comment by n1ru4l** [comment]
This is actually the first time I hear about the usual ember-cli addon build process. :sweat_smile:
I built this addon quickly when I needed it. Would be cool if you could do this, since there is not really a reason why you should not do this. :smile:

**Comment by pichfl** [comment]
See https://ember-cli.com/extending/#developing-addons-and-blueprints for what I meant. I'll try to make this happen in my fork soonish and post a PR.

**Comment by n1ru4l** [comment]
@pichfl Are you still motivated to do this?

**Comment by n1ru4l** [comment]
Closed due to missing feedback.

**Comment by pichfl** [comment]
Incredibly sorry for that. We moved back using ember-cli-sass and ember-cli-postcss directly. I'm still following this addon, but I'd have to do the conversion in my spare development time, which is currently not focussed on JavaScript.
