### ISSUE TITLE
Not working with postcss ^6

### ISSUE THREAD

**Issue by monovertex** [n1ru4l/ember-cli-css-preprocess#36]
See title. The addon throws an error and refuses to work with the latest postcss version.

**Comment by n1ru4l** [comment]
I will check that this weekend - did not notice this issue until now.

**Comment by monovertex** [comment]
@n1ru4l, any progress on this? I can provide a commit to bump the version, but I'm not knowledgeable enough to check for breaking API changes.

**Comment by n1ru4l** [comment]
Sorry for letting you wait. Yeah that would be awesome.
The test should detect any breaking changes, so I would suggest you bump the version and run the tests via `npm test`, If everything goes fine create a PR and I will merge it. 🎉

**Comment by n1ru4l** [comment]
Fixed and deployed in as 1.2.1
