### ISSUE TITLE
Bump of ember-cli-version-checker to 2.0.0 broke this addon...

### ISSUE THREAD

**Issue by dbouwman** [n1ru4l/ember-cli-css-preprocess#38]
Just a heads up that `ember-cli-version-checker` 2.0.0 removed the `.isAbove()` static method on the version checker, as can be seen [here](https://github.com/ember-cli/ember-cli-version-checker/blob/master/src/version-checker.js)

However, `index.js` uses that method [here](https://github.com/n1ru4l/ember-cli-css-preprocess/blob/master/index.js#L48)... which of course fails... 

Fix...
```
shouldSetupRegistryInIncluded: function() {
    let checker = new EmberVersionChecker(this);
    return checker.for('ember-cli').isAbove('0.2.0');
},
```

Will PR this after a meeting... but I think this highlights the issue w/ not using ember's testing system in this addon...

**Comment by dbouwman** [comment]
@n1ru4l Thanks for the quick response on this!

**Comment by n1ru4l** [comment]
@dbouwman Thank you for fixing the issue 🙂
