### ISSUE TITLE
PostCSS Plugins based on file in outputPaths?

### ISSUE THREAD

**Issue by FransTwisk** [n1ru4l/ember-cli-css-preprocess#4]
I really like to use PostCSS in an existing Ember application but it has a build tree with several sass files, defined in outputPaths. This works but I want to use different plugins for each of the sass files. Anyway this is currently possible or could this be added?

**Comment by n1ru4l** [comment]
Why would you want to use different (postcss?) plugins for each stylesheet? IMHO it makes the build process just more complicated, I could implement it, but just if it's really necessary.

**Comment by FransTwisk** [comment]
I agree that it's an edge case. I'm currently moving inline data to a separate file using postcss- [postcss-data-packer](https://github.com/Ser-Gen/postcss-data-packer) but only want to do this on one of the  files.

**Comment by n1ru4l** [comment]
Added this feature in 5364169b7a71a5df8870c6b972dc1c4f401a7362
BUT you must use the original filename not the one from outputPaths.
